<a href="https://colab.research.google.com/github/prasa12/MyPython-Stuff/blob/master/Pytorch/Python_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello")

Hello


In [2]:
!nvidia-smi


Wed Aug 13 04:32:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Crrating Tensors



In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [7]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,8],[5,6]])
MATRIX

tensor([[7, 8],
        [9, 8],
        [5, 6]])

In [10]:
MATRIX.ndim


2

In [11]:
MATRIX.shape

torch.Size([3, 2])

In [12]:
# TENSOR

TENSOR = torch.tensor([[[3, 60, 45],
                        [3,2,4],
                        [7,4,90]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR.ndim

3

### Random Tensors
 Why Random tensors? Neural networks start with random tensors.


In [20]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.6175, 0.4306, 0.4602, 0.3892],
         [0.2488, 0.9522, 0.0659, 0.5640],
         [0.2989, 0.2978, 0.6154, 0.9914]]])

In [21]:
random_tensor.ndim


3

In [25]:
# Create random image tensor
rand_img_tensor = torch.rand(size =(224,235,3))
rand_img_tensor.shape,rand_img_tensor.ndim

(torch.Size([224, 235, 3]), 3)

## Zeros and Ones

In [27]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [29]:
ones.dtype


torch.float32

In [30]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors_like

In [35]:
# Use torch.range()
one_to_ten = torch.arange(0,10)

In [36]:
one_to_ten = torch.arange(start = 0,end =10, step =3)
one_to_ten

tensor([0, 3, 6, 9])

In [38]:
zeros_like1 = torch.zeros_like(input=one_to_ten)
zeros_like1

tensor([0, 0, 0, 0])

## Tensor datatypes


1.   Tensors not right datatype
2.   Tensors not right shape
3.  Tensors not on the right device



In [40]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None, device= None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [41]:
float_32_tensor.dtype

torch.float32

In [44]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor + float_32_tensor


tensor([ 6., 12., 18.])

In [50]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [51]:
int_32_tensor+float_16_tensor


tensor([ 6., 12., 18.], dtype=torch.float16)

### Getting info from tensors
Tensors not right datatype = tenosr.dtype
Tensors not right shape = tensor.shape
Tensors not on the right device = tensor.device

