<a href="https://colab.research.google.com/github/prasa12/MyPython-Stuff/blob/master/Pytorch/Python_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
print("Hello")

Hello


In [6]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


## Pytorch Fundamentals

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Crrating Tensors



In [8]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
scalar.item()

7

In [11]:
# vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [12]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,8],[5,6]])
MATRIX

tensor([[7, 8],
        [9, 8],
        [5, 6]])

In [14]:
MATRIX.ndim


2

In [15]:
MATRIX.shape

torch.Size([3, 2])

In [16]:
# TENSOR

TENSOR = torch.tensor([[[3, 60, 45],
                        [3,2,4],
                        [7,4,90]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR.ndim

3

### Random Tensors
 Why Random tensors? Neural networks start with random tensors.


In [19]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.7672, 0.8782, 0.1794, 0.7687],
         [0.6570, 0.7819, 0.8302, 0.5190],
         [0.8704, 0.4893, 0.8378, 0.7130]]])

In [20]:
random_tensor.ndim


3

In [21]:
# Create random image tensor
rand_img_tensor = torch.rand(size =(224,235,3))
rand_img_tensor.shape,rand_img_tensor.ndim

(torch.Size([224, 235, 3]), 3)

## Zeros and Ones

In [22]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [24]:
ones.dtype


torch.float32

In [25]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors_like

In [26]:
# Use torch.range()
one_to_ten = torch.arange(0,10)

In [27]:
one_to_ten = torch.arange(start = 0,end =10, step =3)
one_to_ten

tensor([0, 3, 6, 9])

In [28]:
zeros_like1 = torch.zeros_like(input=one_to_ten)
zeros_like1

tensor([0, 0, 0, 0])

## Tensor datatypes


1.   Tensors not right datatype
2.   Tensors not right shape
3.  Tensors not on the right device



In [29]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None, device= None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor + float_32_tensor


tensor([ 6., 12., 18.])

In [33]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
int_32_tensor+float_16_tensor


tensor([ 6., 12., 18.], dtype=torch.float16)

### Getting info from tensors
Tensors not right datatype = tenosr.dtype
Tensors not right shape = tensor.shape
Tensors not on the right device = tensor.device



### Matrix Multiplication
1. Element-wise Multiplication
2. Matrix multiplication( dot product)

In [35]:
# Element wise
print(TENSOR,"*", TENSOR)
print(f"Equals: {TENSOR*TENSOR}")

tensor([[[ 3, 60, 45],
         [ 3,  2,  4],
         [ 7,  4, 90]]]) * tensor([[[ 3, 60, 45],
         [ 3,  2,  4],
         [ 7,  4, 90]]])
Equals: tensor([[[   9, 3600, 2025],
         [   9,    4,   16],
         [  49,   16, 8100]]])


In [36]:
torch.matmul(TENSOR,TENSOR)

tensor([[[ 504,  480, 4425],
         [  43,  200,  503],
         [ 663,  788, 8431]]])

In [37]:
%%time
tensor = torch.tensor([1,2,3])
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]

print(value)

tensor(14)
CPU times: user 1.45 ms, sys: 71 µs, total: 1.52 ms
Wall time: 1.29 ms


In [38]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 139 µs, sys: 0 ns, total: 139 µs
Wall time: 228 µs


tensor(14)

In [44]:
### one of the most common errors in DL ( shape errors)
# Shapes for Matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [47]:
## Finding min, max, mean, sum atc
# Create a tensor
x = torch.arange(0, 100, 10)
torch.min(x),x.min()
torch.max(x),x.max()

(tensor(90), tensor(90))

In [49]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [50]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [51]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
x.argmin()

tensor(0)

In [53]:
x.argmax()

tensor(9)

In [54]:
x[9]

tensor(90)

### Reshaping, stacking, sqeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other ( vstack) or side by side(torch.hstack)
*  Squeeze -removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view od the input with dimensions permuted(swapped) in a certain way.

In [65]:
# Lets create a tensor
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [66]:
# Add an extra dimension
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))