<a href="https://colab.research.google.com/github/prasa12/MyPython-Stuff/blob/master/Pytorch/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


## Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Crrating Tensors



In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,8],[5,6]])
MATRIX

tensor([[7, 8],
        [9, 8],
        [5, 6]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX.shape

torch.Size([3, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[3, 60, 45],
                        [3,2,4],
                        [7,4,90]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

### Random Tensors
 Why Random tensors? Neural networks start with random tensors.


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.7672, 0.8782, 0.1794, 0.7687],
         [0.6570, 0.7819, 0.8302, 0.5190],
         [0.8704, 0.4893, 0.8378, 0.7130]]])

In [ ]:
random_tensor.ndim


3

In [ ]:
# Create random image tensor
rand_img_tensor = torch.rand(size =(224,235,3))
rand_img_tensor.shape,rand_img_tensor.ndim

(torch.Size([224, 235, 3]), 3)

## Zeros and Ones

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype


torch.float32

In [ ]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors_like

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(0,10)

In [ ]:
one_to_ten = torch.arange(start = 0,end =10, step =3)
one_to_ten

tensor([0, 3, 6, 9])

In [ ]:
zeros_like1 = torch.zeros_like(input=one_to_ten)
zeros_like1

tensor([0, 0, 0, 0])

## Tensor datatypes


1.   Tensors not right datatype
2.   Tensors not right shape
3.  Tensors not on the right device



In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None, device= None,requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor + float_32_tensor


tensor([ 6., 12., 18.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
int_32_tensor+float_16_tensor


tensor([ 6., 12., 18.], dtype=torch.float16)

### Getting info from tensors
Tensors not right datatype = tenosr.dtype
Tensors not right shape = tensor.shape
Tensors not on the right device = tensor.device



### Matrix Multiplication
1. Element-wise Multiplication
2. Matrix multiplication( dot product)

In [ ]:
# Element wise
print(TENSOR,"*", TENSOR)
print(f"Equals: {TENSOR*TENSOR}")

tensor([[[ 3, 60, 45],
         [ 3,  2,  4],
         [ 7,  4, 90]]]) * tensor([[[ 3, 60, 45],
         [ 3,  2,  4],
         [ 7,  4, 90]]])
Equals: tensor([[[   9, 3600, 2025],
         [   9,    4,   16],
         [  49,   16, 8100]]])


In [ ]:
torch.matmul(TENSOR,TENSOR)

tensor([[[ 504,  480, 4425],
         [  43,  200,  503],
         [ 663,  788, 8431]]])

In [ ]:
%%time
tensor = torch.tensor([1,2,3])
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]

print(value)

tensor(14)
CPU times: user 1.45 ms, sys: 71 µs, total: 1.52 ms
Wall time: 1.29 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 139 µs, sys: 0 ns, total: 139 µs
Wall time: 228 µs


tensor(14)

In [ ]:
### one of the most common errors in DL ( shape errors)
# Shapes for Matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
## Finding min, max, mean, sum atc
# Create a tensor
x = torch.arange(0, 100, 10)
torch.min(x),x.min()
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

### Reshaping, stacking, sqeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other ( vstack) or side by side(torch.hstack)
*  Squeeze -removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view od the input with dimensions permuted(swapped) in a certain way.

In [4]:
# Lets create a tensor
import torch
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [5]:
# Add an extra dimension
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [7]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2,0,1)
print(f"Previous Shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}")

Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [12]:
x_original[1,0,0]

In [13]:
x_permuted[1,0,0]

tensor(0.4540)

# Indexing ( selecting data from tensors)

In [14]:
# Create Tensor
import torch
x= torch.arange(1,10).reshape(1,3,3)

In [15]:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [16]:
# Let's index our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
# Lets index the middle bracket
x[0,1,1]

tensor(5)

In [25]:
# You can also use ":"
x[:,0]

tensor([[1, 2, 3]])

In [26]:
# Get all values of 0th and 1st dimension but only index 1 and 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

# Pytorch tensors and Numpy
Numpy is a popular scientific Python numerical computing torch.library

And because of this, Pytorch has functionality to interact with it.

* Data in Numpy, want in Pytorch tensor ->'torch.torch.from_numpy(ndarray)'
* Pytorch tensor -> Numpy ->'torch.Tensor.numpy()'

In [33]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [34]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [35]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [36]:
torch.rand(3,3)

tensor([[0.1970, 0.3154, 0.5462],
        [0.5623, 0.8394, 0.7330],
        [0.8696, 0.8446, 0.7192]])

In [39]:
Randon_SEED = 42
torch.manual_seed(Randon_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(Randon_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)



tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
