In [3]:
print('hello')

hello


In [5]:
print('new')


new


Comments

In [9]:
3/2


1.5

In [11]:
7/4

1.75

In [13]:
7%4


3

In [15]:
50%5


0

In [17]:
20%2


0

In [19]:
2**3

8

In [1]:
print('Hello');


Hello


In [3]:
print('Hello \n World')


Hello 
 World


In [5]:
len('I am hungry')

11

In [7]:
print(' This is a string {}'. format('INSERTED'))

 This is a string INSERTED


In [11]:
print(' THis is {} {}'.format('fox','brown'))

 THis is fox brown


In [13]:
my_list = [ 1,2,3]

In [15]:
mylist = ['string', 100,23.2]

In [17]:
len(mylist)

3

In [19]:
mylist = ['one','two','three']

In [21]:
mylist[0]


'one'

In [23]:
anot_list = ['four','five']

In [25]:
mylist+anot_list


['one', 'two', 'three', 'four', 'five']

In [27]:
new_list

NameError: name 'new_list' is not defined

In [5]:
%%writefile myfile.txt
I am Prashanti

Writing myfile.txt


In [7]:
myfile = open('myfile.txt')


In [9]:
myfile = open('l.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'l.txt'

In [11]:
pwd

'C:\\Users\\prashany\\MyPython Stuff'

In [19]:
myfile.read()


'I am Prashanti\n'

In [23]:
myfile.seek(0)


0

In [25]:
myfile.readlines()

['I am Prashanti\n']

In [27]:
myfile.close()

In [29]:
with open('myfile.txt') as my_new_file:
    contents = my_new_file.read()

In [31]:
contents

'I am Prashanti\n'

In [37]:
with open('myfile.txt',mode = 'r+') as myfile:
    contents = myfile.read()

In [39]:
contents


'I am Prashanti\n'

In [41]:
with open('ddddddd.txt',mode = 'w') as f:
    f.write(' I created a file')

In [45]:
with open('ddddddd.txt',mode = 'r') as f:
    f.read()

In [3]:
mylist = [1,2,3,4,5,6,7,8,9,10]

In [5]:
for item in mylist:
    print('Hello')

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [9]:
list_sum = 0
for num in mylist:
    list_sum = list_sum + num;

    print(list_sum)

1
3
6
10
15
21
28
36
45
55


In [11]:
my_string = 'Hello World'
for letter in my_string:
    print(letter)

H
e
l
l
o
 
W
o
r
l
d


In [13]:
tup = (1,2,3)
for item in tup:
    print(item)

1
2
3


In [15]:
mylist = [(1,2),(3,4),(5,6),(7,8)]
len(mylist)

4

In [19]:
for (a,b) in mylist:
    print(a)
    print(b)

1
2
3
4
5
6
7
8


In [27]:
d = {'k1':1,'k2':2,'k3':3}
for key,item in d.items():
    print(item)
    print(key)

1
k1
2
k2
3
k3


In [29]:
mylist = [ 1,2,3]


In [39]:
for num in range(3,11,1):
    print(num)

3
4
5
6
7
8
9
10


In [41]:
list(range(0,11,2))

[0, 2, 4, 6, 8, 10]

In [45]:
index_count =0;
for letter in 'abcde':
    print('At index {} the letter is {}'.format(index_count,letter))

At index 0 the letter is a
At index 0 the letter is b
At index 0 the letter is c
At index 0 the letter is d
At index 0 the letter is e


In [47]:
word = 'abcde'

for index,letter in enumerate(word):
    print(index)
    print(letter)
    

0
a
1
b
2
c
3
d
4
e


In [49]:
mylist1 = [1,2,3,4,5]
mylist2 = ['a','b','c','d','e']
for item in zip(mylist1,mylist2):
    print(item)

(1, 'a')
(2, 'b')
(3, 'c')
(4, 'd')
(5, 'e')


In [51]:
list(zip(mylist1,mylist2))

[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd'), (5, 'e')]

In [53]:
split('my word')


NameError: name 'split' is not defined

In [55]:
a = 'my word'
a.split()


['my', 'word']

In [63]:
def myfunc(*args):
    return sum((args))*0.05

In [59]:
myfunc(40,60)

5.0

In [65]:
myfunc(40,50,40)

6.5

In [79]:
name = 'macdonaldhh'


In [81]:
name[:3].capitalize()+name[3:].capitalize()


'MacDonaldhh'

In [83]:
def square(num):
    return num**2

In [85]:
my_nums = [1,2,3,4,5]

In [89]:
for item in map(square,my_nums):
    print(item)

1
4
9
16
25


In [91]:
list(map(square,my_nums))

[1, 4, 9, 16, 25]

In [103]:
list(map(lambda num:num**2,my_nums))

[1, 4, 9, 16, 25]

In [57]:
import numpy as np


In [3]:
mylist = [1,2,3]

In [5]:
type(mylist)


list

In [7]:
myarray = np.array(mylist)

In [11]:

myarray

array([1, 2, 3])

In [13]:
type(myarray)

numpy.ndarray

In [23]:
np.arange(0,10,0)

ZeroDivisionError: division by zero

In [17]:
myarray.data

In [25]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.random.seed(101)

In [37]:
arr = np.random.randint(0,100,10)

In [39]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [41]:
arr.max()


95

In [43]:
arr.argmax()

0

In [45]:
arr.argmin()

7

In [53]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [61]:
mat = np.arange(0,100).reshape(10,10)

In [63]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [65]:
mat[46]

IndexError: index 46 is out of bounds for axis 0 with size 10

In [71]:
mat[:,1].reshape(1,10)


array([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [85]:
mat[0:3,0:4] = 0

In [87]:
ma

<function ndarray.clip>

In [89]:
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [97]:
mynewmat = mat.copy()

In [99]:
mynewmat


array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])